# Generated by Django 5.1.3 on 2024-11-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_csr_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Materialning klassifikatordagi kodi')),
                ('material_name', models.CharField(max_length=1500, verbose_name='Material nomi')),
                ('material_measure', models.CharField(choices=[('MPa', 'Megapaskal'), ('w', 'vatt'), ('kN', 'kiloNyuton'), ('ta', 'dona'), ('%', 'gradus'), ('Db', 'Detsibel'), ('m3', 'metr kub'), ('km', 'kilometr'), ('m2', 'metr kvadrat'), ('kv', 'kilovatt'), ('t', 'tonna'), ('m', 'metr'), ('sm', 'santimetr'), ('N', 'Nyuton'), ('g', 'gramm'), ('kg', 'kilogramm'), ('dm', 'detsimetr'), ('l', 'litr'), ('mm', 'millimetr'), ('Pa', 'paskal'), ('%', 'protsent'), ('шт', 'шт'), ('t', 'temperatura'), ('ml', 'millilitr'), ('Hz', 'gerts'), ('C', 'selsiy'), ('A', 'amper')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi')),
            ],
            options={
                'db_table': 'material_resources',
                'ordering': ['material_name', 'material_csr_code'],
            },
        ),
    ]
