# Generated by Django 5.1.3 on 2024-11-27 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material_measure',
            field=models.CharField(choices=[('w', 'vatt'), ('kN', 'kiloNyuton'), ('sm', 'santimetr'), ('N', 'Nyuton'), ('km', 'kilometr'), ('MPa', 'Megapaskal'), ('kv', 'kilovatt'), ('%', 'protsent'), ('ml', 'millilitr'), ('g', 'gramm'), ('ta', 'dona'), ('%', 'gradus'), ('m2', 'metr kvadrat'), ('t', 'tonna'), ('шт', 'шт'), ('Hz', 'gerts'), ('m3', 'metr kub'), ('l', 'litr'), ('A', 'amper'), ('dm', 'detsimetr'), ('kg', 'kilogramm'), ('Db', 'Detsibel'), ('mm', 'millimetr'), ('C', 'selsiy'), ('m', 'metr'), ('t', 'temperatura'), ('Pa', 'paskal')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi'),
        ),
        migrations.CreateModel(
            name='Materials_customer',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('material_csr_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Materialning klassifikatordagi kodi')),
                ('material_name', models.CharField(max_length=1500, verbose_name='Material nomi')),
                ('material_measure', models.CharField(choices=[('w', 'vatt'), ('kN', 'kiloNyuton'), ('sm', 'santimetr'), ('N', 'Nyuton'), ('km', 'kilometr'), ('MPa', 'Megapaskal'), ('kv', 'kilovatt'), ('%', 'protsent'), ('ml', 'millilitr'), ('g', 'gramm'), ('ta', 'dona'), ('%', 'gradus'), ('m2', 'metr kvadrat'), ('t', 'tonna'), ('шт', 'шт'), ('Hz', 'gerts'), ('m3', 'metr kub'), ('l', 'litr'), ('A', 'amper'), ('dm', 'detsimetr'), ('kg', 'kilogramm'), ('Db', 'Detsibel'), ('mm', 'millimetr'), ('C', 'selsiy'), ('m', 'metr'), ('t', 'temperatura'), ('Pa', 'paskal')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_resources_customer',
                'ordering': ['material_name', 'material_csr_code'],
            },
        ),
    ]
