# Generated by Django 5.1.3 on 2024-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_materials', '0002_alter_materials_material_measure_materials_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material_measure',
            field=models.CharField(choices=[('m3', 'metr kub'), ('A', 'amper'), ('ta', 'dona'), ('km', 'kilometr'), ('шт', 'шт'), ('Db', 'Detsibel'), ('t', 'temperatura'), ('w', 'vatt'), ('Hz', 'gerts'), ('Pa', 'paskal'), ('N', 'Nyuton'), ('dm', 'detsimetr'), ('sm', 'santimetr'), ('%', 'gradus'), ('t', 'tonna'), ('m', 'metr'), ('mm', 'millimetr'), ('kg', 'kilogramm'), ('kv', 'kilovatt'), ('MPa', 'Megapaskal'), ('m2', 'metr kvadrat'), ('kN', 'kiloNyuton'), ('C', 'selsiy'), ('l', 'litr'), ('%', 'protsent'), ('ml', 'millilitr'), ('g', 'gramm')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi'),
        ),
        migrations.AlterField(
            model_name='materials_customer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materials_customer',
            name='material_measure',
            field=models.CharField(choices=[('m3', 'metr kub'), ('A', 'amper'), ('ta', 'dona'), ('km', 'kilometr'), ('шт', 'шт'), ('Db', 'Detsibel'), ('t', 'temperatura'), ('w', 'vatt'), ('Hz', 'gerts'), ('Pa', 'paskal'), ('N', 'Nyuton'), ('dm', 'detsimetr'), ('sm', 'santimetr'), ('%', 'gradus'), ('t', 'tonna'), ('m', 'metr'), ('mm', 'millimetr'), ('kg', 'kilogramm'), ('kv', 'kilovatt'), ('MPa', 'Megapaskal'), ('m2', 'metr kvadrat'), ('kN', 'kiloNyuton'), ('C', 'selsiy'), ('l', 'litr'), ('%', 'protsent'), ('ml', 'millilitr'), ('g', 'gramm')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi'),
        ),
    ]
