# Generated by Django 5.1.3 on 2024-11-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_materials', '0003_alter_materials_material_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material_measure',
            field=models.CharField(choices=[('kg', 'kilogramm'), ('m2', 'metr kvadrat'), ('dm', 'detsimetr'), ('m', 'metr'), ('t', 'tonna'), ('m3', 'metr kub'), ('C', 'selsiy'), ('Db', 'Detsibel'), ('шт', 'шт'), ('km', 'kilometr'), ('mm', 'millimetr'), ('N', 'Nyuton'), ('Hz', 'gerts'), ('ml', 'millilitr'), ('l', 'litr'), ('kN', 'kiloNyuton'), ('%', 'gradus'), ('sm', 'santimetr'), ('MPa', 'Megapaskal'), ('w', 'vatt'), ('A', 'amper'), ('g', 'gramm'), ('%', 'protsent'), ('Pa', 'paskal'), ('ta', 'dona'), ('t', 'temperatura'), ('kv', 'kilovatt')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi'),
        ),
        migrations.AlterField(
            model_name='materials_customer',
            name='customer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materials_customer',
            name='material_measure',
            field=models.CharField(choices=[('kg', 'kilogramm'), ('m2', 'metr kvadrat'), ('dm', 'detsimetr'), ('m', 'metr'), ('t', 'tonna'), ('m3', 'metr kub'), ('C', 'selsiy'), ('Db', 'Detsibel'), ('шт', 'шт'), ('km', 'kilometr'), ('mm', 'millimetr'), ('N', 'Nyuton'), ('Hz', 'gerts'), ('ml', 'millilitr'), ('l', 'litr'), ('kN', 'kiloNyuton'), ('%', 'gradus'), ('sm', 'santimetr'), ('MPa', 'Megapaskal'), ('w', 'vatt'), ('A', 'amper'), ('g', 'gramm'), ('%', 'protsent'), ('Pa', 'paskal'), ('ta', 'dona'), ('t', 'temperatura'), ('kv', 'kilovatt')], default='kg', max_length=25, verbose_name='Material o‘lchov birligi'),
        ),
    ]
